backend:
  name: git-gateway
  branch: main
  repo: ABmawouli/sg2d-togo
  identity_url: https://sg2d-togo.netlify.app/.netlify/identity
  gateway_url: https://sg2d-togo.netlify.app/.netlify/git

media_folder: "imgs/uploads"
public_folder: "/imgs/uploads"

publish_mode: editorial_workflow

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Catégorie", name: "category", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
